name: Atualizar

# Controla quando o workflow vai ser executado
on:
  # https://crontab.guru/#0_12_*_*_*
  # Atualmente configurado para executar a todo dia, √†s 12:00 AM.
  schedule:
    # Formato do cron:
    # Minuto Hora Dia-do-M√™s M√™s Dia-da-Semana
    - cron: "0 12 * * *"
  # Permite executar manualmente este workflow pela aba Actions
  workflow_dispatch:

jobs:
  Atualizar:
    runs-on: ubuntu-latest
    env:
      PUSH: 1
      BAIXAR: 1
      CRIAR: 1
      ATUALIZAR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Verificar atualiza√ß√µes e atualizar o reposit√≥rio
      - name: Verificar se h√° atualiza√ß√£o üîé
        run: |
          function comparar (){
            atual_maior=$(echo "$1" | cut -d "." -f 1)
            atual_medio=$(echo "$1" | cut -d "." -f 2)
            atual_menor=$(echo "$1" | cut -d "." -f 3 | cut -d "-" -f 1)

            recente_maior=$(echo "$2" | cut -d "." -f 1)
            recente_medio=$(echo "$2" | cut -d "." -f 2)
            recente_menor=$(echo "$2" | cut -d "." -f 3 | cut -d "-" -f 1)

            if [ "$recente_maior" -gt "$atual_maior" ]; then
              return 0
            fi
            if [ "$recente_medio" -gt "$atual_medio" ]; then
              return 0
            fi
            if [ "$recente_menor" -gt "$atual_menor" ]; then
              return 0
            fi
            return 1
          }

          recente=$(curl -s "https://api.github.com/repos/InioX/matugen/releases" | grep -Po '"tag_name": "v\K[^"]*' | head -1)
          echo "Ultima vers√£o lan√ßada: ${recente}"
          echo "RECENTE=${recente}" >> $GITHUB_ENV
          if [ -f 'versao_atual' ]; then
            atual=$(cat versao_atual)
            echo "Vers√£o atual: ${atual}"
            echo "Comparando vers√µes..."
            if comparar "${atual}" "${recente}"; then
              echo "Atualiza√ß√£o identificada."
              echo "BAIXAR=0" >> $GITHUB_ENV
            else
              echo "N√£o h√° atualiza√ß√£o."
            fi
          else
            echo "N√£o sei qual √© a vers√£o atual, por isso vou for√ßar uma atualiza√ß√£o."
            echo "BAIXAR=0" >> $GITHUB_ENV
          fi
      - name: Baixar atualiza√ß√£o üî•
        if: ${{ env.BAIXAR == 0 }}
        run: |
          function baixar_atualizacao() {
            versao=$(echo "$1" | cut -d "-" -f 1)

            echo "Baixando bin√°rio: x86_64"
            wget -q "https://github.com/InioX/matugen/releases/download/v$1/matugen-${versao}-x86_64.tar.gz"
            if [ "$?" -eq "0" ]; then
              echo "Concluido"
            else
              return 1
            fi

            return 0
          }

          if baixar_atualizacao "${{ env.RECENTE }}"; then
            echo "CRIAR=0" >> $GITHUB_ENV
          else
            echo "Erro ao baixar o arquivo."
          fi
      # Criar arquivo deb
      - name: Criar arquivo deb üõ†Ô∏è
        if: ${{ env.CRIAR == 0 }}
        run: |
          function criar_arquivo_deb() {
            versao=$(echo "$1" | cut -d "-" -f 1)

            echo "Descompactando bin√°rios: x86_64"
            mkdir -p "x86_64"
            tar zxf "matugen-${versao}-x86_64.tar.gz" -C "x86_64"

            echo "Montando estrutura debian: x86_64"
            mkdir -p matugen/usr/bin
            mkdir -p matugen/DEBIAN

            echo "Movendo bin√°rios: x86_64"
            mv "x86_64/matugen" "matugen/usr/bin/matugen"

            echo "Escrevendo informa√ß√µes do pacote: x86_64"
            cat << X0 > matugen/DEBIAN/control
          Package: matugen
          Version: $1
          Section: default
          Priority: optional
          Architecture: amd64
          Maintainer: Maeglithier
          Description: A material you color generation tool.
          X0

            echo "Compilando arquivo deb: x86_64"
            dpkg-deb --root-owner-group --build matugen
          }

          if criar_arquivo_deb "${{ env.RECENTE }}"; then
            echo "ATUALIZAR=0" >> $GITHUB_ENV
          else
            echo "Erro ao criar arquivo deb."
          fi
      # Importar a chave PGP privada e Informar suas informa√ß√µes
      - name: Importar chave PGP üîë
        if: ${{ env.ATUALIZAR == 0 }}
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Informar chave importada ‚úÖ
        if: ${{ env.ATUALIZAR == 0 }}
        run: |
          echo "fingerprint : ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid       : ${{ steps.import_gpg.outputs.keyid }}"
          echo "name        : ${{ steps.import_gpg.outputs.name }}"
      # Organizar reposit√≥rio apt e realizar o push
      - name: Instalar depend√™ncias üî®
        if: ${{ env.ATUALIZAR == 0 }}
        run: |
          sudo apt install reprepro
      - name: Atualizar reposit√≥rio APT üö®
        if: ${{ env.ATUALIZAR == 0 }}
        run: |
          function atualizar_repositorio() {
            versao=$(echo "$1" | cut -d "-" -f 1)
            reprepro --basedir "$(pwd)/meta" includedeb stable "./matugen.deb"
            if [ -d dists ]; then rm -r dists; fi
            if [ -d pool ]; then rm -r pool; fi
            mv meta/dists ./
            mv meta/pool ./
            checksum_amd64=$(sha256sum pool/main/m/matugen/matugen_${versao}_amd64.deb)
            sed -i -E "s,[a-f0-9]{64}[ ]+pool/main/m/matugen/matugen_[0-9]+\.[0-9]+\.[0-9]+_amd64.deb,$checksum_amd64," README.md
            echo "PUSH=0" >> $GITHUB_ENV
          }

          atualizar_repositorio "${{ env.RECENTE }}"
          echo "${{ env.RECENTE }}" > versao_atual
      - uses: EndBug/add-and-commit@v9
        if: ${{ env.PUSH == 0 }}
        with:
          message: "Atualizando os pacotes"
          add: "versao_atual dists pool README.md"
          default_author: github_actions
